'''Tests of the REST API generated by `slapdash.web.web_api`.'''
import pytest
from fastapi.testclient import TestClient

import slapdash
from slapdash.model import Model
from slapdash.web import web_api, format_url, get_shape, nested_list_type
from typing import List


class Sub:
    x = 1.0


class Interface:
    '''An interface docstring'''
    number = 1
    text = 'hello'
    flags = [True, False]
    matrix = [[1, 2], [3, 4]]
    _hidden = 3

    def __init__(self):
        self.sub = Sub()
        self.subs = [Sub(), Sub()]

    @property
    def readonly(self) -> float:
        return 0.5

    def add(self, a: int, b: int = 2) -> int:
        '''adds numbers'''
        return a + b


@pytest.fixture
def interface():
    return Interface()


@pytest.fixture
def client(interface):
    app = web_api(Model(interface), info={'name': 'test'})
    with TestClient(app) as client:
        yield client


def test_meta_endpoints(client):
    assert client.get('/version').json() == slapdash.__version__
    assert client.get('/name').json() == 'Interface'
    assert client.get('/info').json() == {'name': 'test'}
    props = client.get('/get_props').json()
    assert set(props) == {'number', 'text', 'flags', 'matrix', 'sub', 'subs', 'readonly', 'add'}
    assert props['readonly']['readonly'] is True
    assert props['add']['args'] == [['a', 'int'], ['b', 'int']]
    assert client.get('/get_props', params={'name': 'sub'}).json() == props['sub']['type']
    assert client.get('/get_props', params={'name': 'number'}).json() is None


def test_get_param(client):
    assert client.get('/get_param', params={'name': 'number'}).json() == 1
    assert client.get('/get_param', params={'name': 'sub.x'}).json() == 1.0
    assert client.get('/get_param', params={'name': 'subs[1].x'}).json() == 1.0
    assert client.get('/get_param', params={'name': 'matrix'}).json() == [[1, 2], [3, 4]]


def test_get_set_values(client, interface):
    assert client.get('/number').json() == 1
    assert client.post('/number', params={'value': 5}).json() == 5
    assert interface.number == 5

    assert client.post('/text', params={'value': 'world'}).json() == 'world'
    assert interface.text == 'world'

    assert client.post('/sub/x', params={'value': 2.5}).json() == 2.5
    assert interface.sub.x == 2.5

    assert client.post('/subs/1/x', params={'value': 3.5}).json() == 3.5
    assert interface.subs[1].x == 3.5
    assert interface.subs[0].x == 1.0
    assert client.get('/subs/1/x').json() == 3.5


def test_list_endpoints(client, interface):
    assert client.get('/flags').json() == [True, False]
    assert client.get('/flags/1').json() is False
    assert client.post('/flags/1', params={'value': True}).json() is True
    assert interface.flags == [True, True]

    assert client.get('/matrix/1/0').json() == 3
    assert client.post('/matrix/1/0', params={'value': 9}).json() == 9
    assert interface.matrix == [[1, 2], [9, 4]]


def test_readonly(client):
    assert client.get('/readonly').json() == 0.5
    assert client.post('/readonly', params={'value': 1.0}).status_code == 405


def test_validation(client, interface):
    response = client.post('/number', params={'value': 'abc'})
    assert response.status_code == 422
    assert interface.number == 1


def test_method(client):
    assert client.post('/add', params={'a': 1}).json() == 3
    assert client.post('/add', params={'a': 1, 'b': 5}).json() == 6
    assert client.post('/add').status_code == 422


def test_openapi(client):
    schema = client.get('/openapi.json').json()
    assert schema['info']['title'] == 'Slapdash Interface: Interface'
    assert '/number' in schema['paths']
    assert '/subs/{index0}/x' in schema['paths']


def test_frontend(client):
    response = client.get('/')
    assert response.status_code == 200
    assert '<div id="root">' in response.text
    assert client.get('/index.js').status_code == 200


def test_custom_css(tmp_path):
    css = tmp_path / 'custom.css'
    css.write_text('body { color: red; }')
    app = web_api(Model(Interface()), css=str(css))
    with TestClient(app) as client:
        assert client.get('/custom.css').text == 'body { color: red; }'


def test_format_url():
    assert format_url('a') == ('/a', ())
    assert format_url('a.b[3].c[2]') == ('/a/b/{index0}/c/{index1}', ('index0', 'index1'))
    assert format_url('a[]') == ('/a/{index0}', ('index0',))


def test_shape_helpers():
    assert get_shape([1, 2, 3]) == (3,)
    assert get_shape([[1, 2], [3, 4], [5, 6]]) == (3, 2)
    assert get_shape('abc') == ()
    with pytest.raises(ValueError):
        get_shape([[1, 2], [3]])
    assert nested_list_type(int, 2) == List[List[int]]
